### PR TITLE
Added PHP Library pantry-cloud to SDK's

### PR DESCRIPTION
**Pull request by sebaOfficial**
Added [PHP ](https://github.com/sebaOfficial/pantry-cloud)Library pantry-cloud to SDK's

### CODE REVIEW

**Comment by imRohan** [comment]
Great work!

I'd request the PR (& commit message) be reworded to be more in line with [other PRs like this. ](https://github.com/imRohan/Pantry/pull/162)

Thanks!

**Comment by sebaOfficial** [comment]
What do you mean?

Il giorno mer 27 lug 2022 alle ore 19:06 Rohan Likhite <
***@***.***> ha scritto:

**Comment by imRohan** [comment]
@sebaOfficial Rename this PR and your commit message to "Added PHP Library pantry-cloud to SDK's". The current title "Update sdk.ts" is not descriptive enough.

**Comment by sebaOfficial** [comment]
@imRohan I have no idea of how to change th ecommit message :')

**Comment by imRohan** [comment]
@sebaOfficial Try to follow this: https://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote

**Comment by sebaOfficial** [comment]
@imRohan It was easier then it looked like, is everything alright now?

**Comment by imRohan** [comment]
@sebaOfficial Close! But i believe you've renamed the PR, but not the actually commit itself.

The commit (df5b3066985b0f06fbb4dadf1582f7daf98e6e9e) still has the old commit message: 
image

**Pull request merged**
