### PR TITLE
Removed request dependency

### PR DESCRIPTION
**Pull request by kaffarell**
The request dependency is deprecated and should not be used (https://www.npmjs.com/package/request). We also didn't use it in the project, so we deleted it.

### CODE REVIEW

**Comment by imRohan** [comment]
Good catch, lets go ahead and remove it!

Happy to get this PR merged int, just update your PR/Commit message and ill hit the button. 💪

**Comment by kaffarell** [comment]
Hmm, do you know why the ci run failed @imRohan ? Seems like an error in the coveralls action.

**Comment by imRohan** [comment]
> Hmm, do you know why the ci run failed @imRohan ? Seems like an error in the coveralls action.

Seems like the 405 error is related to this issue (linked below). Coveralls is down. 👎 

https://stackoverflow.com/questions/69247002/fix-405-not-allowed-error-with-coveralls

**Comment by kaffarell** [comment]
Can you manually run the action again after the issue at coveralls is resolved?

**Comment by imRohan** [comment]
> Can you manually run the action again after the issue at coveralls is resolved?

Yes, ill keep an eye on it and re-run the actions once Coveralls is back online.

**Pull request merged**
