### PR TITLE
Added GO client sdk

### PR DESCRIPTION
**Pull request by Atoo35**
updated sdk component to add go client details

### CODE REVIEW

**Comment by Atoo35** [comment]
@imRohan

**Review by imRohan — APPROVED** [review]

**Comment by imRohan** [comment]
Awesome work!

**Comment by Atoo35** [comment]
THanks @imRohan , quick question shouldnt the SDK page reflect the change?

**Comment by imRohan** [comment]
@Atoo35 Yes, however the change hasn't been deployed yet. I'll get to it this weekend

**Comment by Atoo35** [comment]
Ahh ok ok, I thought ci/cd is setup.. no worries

**Comment by imRohan** [comment]
@Atoo35 Changes were deployed :)

**Pull request merged**
